// File generated by FlutterFire CLI.
// This file should be updated with your actual Firebase project configuration
// Run `flutterfire configure` to generate this file with your project settings
//
// ⚠️ IMPORTANT: The values below are TEMPLATES and will NOT work in production!
// You MUST replace these with your actual Firebase project configuration.
// Attempting to run the app with these placeholder values will cause Firebase
// initialization to fail.
//
// To configure Firebase properly:
// 1. Install Firebase CLI: npm install -g firebase-tools
// 2. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 3. Run: flutterfire configure
// 4. Select your Firebase project and platforms
//
// The FlutterFire CLI will automatically replace this file with correct values.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8bEj_N6z-kqFGBS0pDHomRGO5NaGVEzU',
    appId: '1:195093019449:web:80c5c09ca6b7f409e8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    authDomain: 'kenwellmobileapp.firebaseapp.com',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bEj_N6z-kqFGBS0pDHomRGO5NaGVEzU',
    appId: '1:195093019449:android:80c5c09ca6b7f409e8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8bEj_N6z-kqFGBS0pDHomRGO5NaGVEzU',
    appId: '1:195093019449:ios:80c5c09ca6b7f409e8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
    iosBundleId: 'com.example.kenwellHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8bEj_N6z-kqFGBS0pDHomRGO5NaGVEzU',
    appId: '1:195093019449:ios:80c5c09ca6b7f409e8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
    iosBundleId: 'com.example.kenwellHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8bEj_N6z-kqFGBS0pDHomRGO5NaGVEzU',
    appId: '1:195093019449:web:80c5c09ca6b7f409e8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
  );
}
