// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate this file after adding platforms
// or changing your Firebase project.
//
// ── API Key Security for Web & Desktop ────────────────────────────────────────
// The API keys in this file are intentionally included in source control.
// Firebase/Google designed client API keys to be public — they identify your
// project but do NOT grant privileged access on their own. Security is enforced
// through:
//   1. Firebase Security Rules (Firestore / Storage / Realtime DB)
//   2. Firebase Authentication (only authenticated users can read/write)
//   3. Google Cloud Console → APIs & Services → Credentials:
//        • WEB:     Restrict the key to your domain(s) under "HTTP referrers"
//        • DESKTOP: Restrict the key to your bundle/package ID under "Apps"
//   4. Firebase App Check (recommended for production) — adds attestation
//        so only your genuine app binaries can call Firebase APIs.
//
// See: https://firebase.google.com/docs/projects/api-keys
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqT0ufmplscZlbzli8OHMjIAr65mPeenw',
    appId: '1:195093019449:web:c89084426a9ef208e8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    authDomain: 'kenwellmobileapp.firebaseapp.com',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
    measurementId: 'G-N7N7RPDECH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bEj_N6z-kqFGBS0pDHomRGO5NaGVEzU',
    appId: '1:195093019449:android:80c5c09ca6b7f409e8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFD7K4angQpTSZ2cJl6ianO_Yw_19ggg',
    appId: '1:195093019449:ios:2ed9a3d5c4d8947ce8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
    iosBundleId: 'com.kenwell.healthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFFD7K4angQpTSZ2cJl6ianO_Yw_19ggg',
    appId: '1:195093019449:ios:2ed9a3d5c4d8947ce8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
    iosBundleId: 'com.example.kenwellHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqT0ufmplscZlbzli8OHMjIAr65mPeenw',
    appId: '1:195093019449:web:390b28f01bc90c1ce8c6e8',
    messagingSenderId: '195093019449',
    projectId: 'kenwellmobileapp',
    authDomain: 'kenwellmobileapp.firebaseapp.com',
    storageBucket: 'kenwellmobileapp.firebasestorage.app',
    measurementId: 'G-1CWEC7098X',
  );

}